# Generated by Django 5.0.6 on 2024-07-08 12:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0003_alter_entry_image'),
        ('favoritos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('user', 'entry')},
        ),
    ]
